on:
  rss:
    url: https://github.com/yichengchen/clashX/releases.atom
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://sctapi.ftqq.com/SCT141TMY31JofyEF7NKBnEmUdMrIgp.send 
          method: POST
          body: |
            {
              "title":"clashx更新啦！${{ on.rss.outputs.link }}", 
              "desp": "${{ on.rss.outputs.title }}",
            }
   
